apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: bh1750-ble-instance-01
  labels:
    description: bh1750
    model: bh1750-ble-model
spec:
  deviceModelRef:
    name: bh1750-ble-model
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: "kubernetes.io/hostname"
            operator: In
            values:
              - jetsonnano.edge #pls give your edge node name
  protocol:
    bluetooth:
      macAddress: "8C:CE:4E:83:25:52"
  propertyVisitors:
    - propertyName: lux
      bluetooth:
        characteristicUUID: fd01


status:
  twins:
    - propertyName: lux
