apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: devices.devices.kubeedge.io
spec:
  group: devices.kubeedge.io
  names:
    kind: Device
    plural: devices
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion定义了对象表示的版本化模式。服务器会将可识别的模式转换为最新的内部值，同时可能拒绝不可识别的值。更多信息: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'kind是一个字符串值，表示了这个对象所代表的REST资源。服务器可以从客户端向其提交请求的端点推断出这一点，无法更新。使用驼峰式大小写。更多信息:https://git.k8s.io/community/contributor/dev/API-convents.MD # type-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            deviceModelRef:
              description: '必选: DeviceModelRef 是通过对用作模板的 DeviceModel 的引用来创建设备实例'
              type: object
            nodeSelector:
              description: 'NodeSelector 指示设备和节点之间的绑定首选项更多详情请参考 k8s.io/kubernetes/pkg/apis/core 节点选择器'
              type: object
            protocol:
              description: '必选：用于连接设备的协议配置'
              properties:
                bluetooth:
                  description: '蓝牙的协议配置'
                  properties:
                    macAddress:
                      description: '分配给设备的唯一标识符'
                      type: string
                  type: object
                modbus:
                  description: 'modbus协议配置'
                  properties:
                    slaveID:
                      description: '必选： 范围0-255'
                      format: int64
                      type: integer
                      minimum: 0
                      maximum: 255
                  required:
                    - slaveID
                  type: object
                opcua:
                  description: 'opc-ua协议配置'
                  properties:
                    certificate:
                      description: '访问 opc 服务器的证书'
                      type: string
                    password:
                      description: '访问 opc 服务器的密码'
                      type: string
                    privateKey:
                      description: '用于访问 opc 服务器的私钥'
                      type: string
                    securityMode:
                      description: '默认为 "none"'
                      type: string
                    securityPolicy:
                      description: '默认为 "none"'
                      type: string
                    timeout:
                      description: '服务器连接的超时秒数'
                      format: int64
                      type: integer
                    url:
                      description: '必选: opc 服务器端点的网址'
                      type: string
                    userName:
                      description: '访问 opc 服务器的用户名'
                      type: string
                  required:
                    - url
                  type: object
                common:
                  description: '协议公共部分的配置'
                  properties:
                    com:
                      properties:
                        baudRate:
                          description: '必选：波特率 115200|57600|38400|19200|9600|4800|2400|1800|1200|600|300|200|150|134|110|75|50'
                          format: int64
                          type: integer
                          enum:
                            - 115200
                            - 57600
                            - 38400
                            - 19200
                            - 9600
                            - 4800
                            - 2400
                            - 1800
                            - 1200
                            - 600
                            - 300
                            - 200
                            - 150
                            - 134
                            - 110
                            - 75
                            - 50
                        dataBits:
                          description: '必选：有效值有 8, 7, 6, 5.'
                          format: int64
                          type: integer
                          enum:
                            - 8
                            - 7
                            - 6
                            - 5
                        parity:
                          description: '必选：有效选项有 "none", "even", "odd". Defaults to "none".'
                          type: string
                          enum:
                            - none
                            - even
                            - odd
                        serialPort:
                          description: '必选'
                          type: string
                        stopBits:
                          description: '必选：停止位选 1|2'
                          format: int64
                          type: integer
                          enum:
                            - 1
                            - 2
                      required:
                        - baudRate
                        - dataBits
                        - parity
                        - serialPort
                        - stopBits
                      type: object
                    tcp:
                      properties:
                        ip:
                          description: '必选'
                          type: string
                        port:
                          description: '必选'
                          format: int64
                          type: integer
                      required:
                        - ip
                        - port
                      type: object
                    commType:
                      description: '通信类型，如 tcp 客户端、tcp 服务器或 COM'
                      type: string
                    reconnTimeout:
                      description: '重新连接超时的时长'
                      type: integer
                    reconnRetryTimes:
                      description: '重新连接重试次数'
                      type: integer
                    collectTimeout:
                      description: '定义从设备收集的 Mapper 超时时长'
                      format: int64
                      type: integer
                    collectRetryTimes:
                      description: '定义 Mapper 将从设备收集的重试次数'
                      format: int64
                      type: integer
                    collectType:
                      description: '定义收集类型，同步或异步'
                      type: string
                      enum:
                        - sync
                        - async
                    customizedValues:
                      description: '为提供的协议定制需要的参变量'
                      type: object
                  type: object
                customizedProtocol:
                  description: '定制协议的配置'
                  properties:
                    protocolName:
                      description: '协议名称'
                      type: string
                    configData:
                      description: '自定义的配置参数'
                      type: object
                  required:
                    - protocolName
                  type: object
              type: object
            propertyVisitors:
              description: '必选： 描述如何访问设备属性的 Property Visitors 列表 PropertyVisitors 中 propertyVisitor.propertyName 必须是独一无二的'
              items:
                properties:
                  bluetooth:
                    description: 'Bluetooth 代表蓝牙协议的一组附加 Visitor 配置字段'
                    properties:
                      characteristicUUID:
                        description: '必选: 通信操作的唯一标识'
                        type: string
                      dataConverter:
                        description: '负责将蓝牙设备读取的数据转换成平台可以理解的形式'
                        properties:
                          endIndex:
                            description: '必选: 指定要考虑转换数据的传入字节流的结束索引，指定的值会包含在内，例如，如果指定了3，则它包含第三个索引'
                            format: int64
                            type: integer
                          orderOfOperations:
                            description: '指定操作的执行顺序(将输入数据转换为可理解的形式时需要执行的操作)'
                            items:
                              properties:
                                operationType:
                                  description: '必选: 指定转换传入数据时要执行的操作'
                                  type: string
                                  enum:
                                    - Add
                                    - Subtract
                                    - Multiply
                                    - Divide
                                operationValue:
                                  description: '必选: 指定要用什么值执行操作'
                                  format: double
                                  type: number
                              type: object
                            type: array
                          shiftLeft:
                            description: '如果转换需要左移操作，则指定左移的位数'
                            format: int64
                            type: integer
                          shiftRight:
                            description: '如果转换需要右移操作，则指定右移的位数'
                            format: int64
                            type: integer
                          startIndex:
                            description: '必选: 指定要考虑转换数据的传入字节流的起始索引；例如: 起始索引:2，结束索引:3 连接传入字节流的第二个和第三个索引处的值。如果我们想颠倒顺序，我们可以给它一个开始索引:3，结束索引:2'
                            format: int64
                            type: integer
                        required:
                          - endIndex
                          - startIndex
                        type: object
                      dataWrite:
                        description: '负责将来自平台的数据转换成蓝牙设备能够理解的形式；例如: "ON":[1], "OFF":[0]'
                        type: object
                    required:
                      - characteristicUUID
                    type: object
                  modbus:
                    description: 'Modbus 表示 Modbus 协议的一组附加 Visitor 配置字段'
                    properties:
                      isRegisterSwap:
                        description: '指示高低寄存器是否交换；默认为 false'
                        type: boolean
                      isSwap:
                        description: '指示高字节和低字节是否交换；默认为 false'
                        type: boolean
                      limit:
                        description: '必选: 限制读/写的寄存器数量'
                        format: int64
                        type: integer
                      offset:
                        description: '必选: 偏移量 表示读/写数据的起始寄存器号'
                        format: int64
                        type: integer
                      register:
                        description: '必选: 寄存器类型'
                        type: string
                        enum:
                          - CoilRegister
                          - DiscreteInputRegister
                          - InputRegister
                          - HoldingRegister
                      scale:
                        description: '将原始属性数据转换为最终单位的比例；默认是 1.0'
                        format: double
                        type: number
                    required:
                      - limit
                      - offset
                      - register
                    type: object
                  opcua:
                    description: 'Opcua 代表 opc-ua 协议的一组附加的 Visitor 配置字段'
                    properties:
                      browseName:
                        description: 'opc-ua 节点的名称'
                        type: string
                      nodeID:
                        description: '必选: opc-ua 节点的 ID ，如“ ns=1，i=1005 ”'
                        type: string
                    required:
                      - nodeID
                    type: object
                  customizedProtocol:
                    description: '自定义协议'
                    properties:
                      protocolName:
                        description: '协议名称'
                        type: string
                      configData:
                        description: '定制的参变量'
                        type: object
                    required:
                      - protocolName
                      - configData
                    type: object
                  propertyName:
                    description: '必选: 要访问的设备属性名。这应该指向 DeviceModel 中定义的设备属性的其中一个'
                    type: string
                  reportCycle:
                    description: '定义 Mapper 报告数据的频率'
                    format: int64
                    type: integer
                  collectCycle:
                    description: '定义 Mapper 从设备收集数据的频率'
                    format: int64
                    type: integer
                  customizedValues:
                    description: '为所提供协议的 Visitor 定制参变量'
                    type: object
                required:
                  - propertyName
                type: object
              type: array
            data:
              description: '数据部分描述了应该在边缘节点上处理的时间序列属性的列表'
              properties:
                dataTopic:
                  description: 'Mapper 使用的主题，从数据属性收集的所有数据需要使用该主题进行发布；默认值为 $ke/events/device/+/data/update'
                  type: string
                dataProperties:
                  description: '必选：不需要edgecore来处理的数据属性列表'
                  items:
                    properties:
                      propertyName:
                        description: '必选: 应由外部应用来处理的属性名；该属性应该出现在 DeviceModel 中'
                        type: string
                      metadata:
                        description: '报告值时的时间戳等附加元数据'
                        type: object
                    required:
                      - propertyName
                    type: object
                  type: array
              type: object
          required:
            - deviceModelRef
            - nodeSelector
          type: object
        status:
          properties:
            twins:
              description: '包含 desired/reported 的 device twin 属性值列表；被动设备不会有twin属性，该列表可能为空'
              items:
                properties:
                  desired:
                    description: '必选: desired 的属性值'
                    properties:
                      metadata:
                        description: '报告值时的时间戳等附加元数据'
                        type: object
                      value:
                        description: '必选: 该属性的值'
                        type: string
                    required:
                      - value
                    type: object
                  propertyName:
                    description: '必选: 指定了 desired/reported 值的属性名；该属性应该出现在 DeviceModel 中'
                    type: string
                  reported:
                    description: '必选: reported 的属性值'
                    properties:
                      metadata:
                        description: '报告值时的时间戳等附加元数据'
                        type: object
                      value:
                        description: '必选: 该属性的值'
                        type: string
                    required:
                      - value
                    type: object
                required:
                  - propertyName
                type: object
              type: array
          type: object
  version: v1alpha2
