apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: dth11-ble-instance-01
  labels:
    description: dth11
    model: dth11-ble
spec:
  deviceModelRef:
    name: dth11-ble
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: "kubernetes.io/hostname"
            operator: In
            values:
              - jetson #pls give your edge node name
  protocol:
    bluetooth:
      macAddress: "8C:CE:4E:83:25:52"
  propertyVisitors:
    - propertyName: temperature
      bluetooth:
        characteristicUUID: fd01
    - propertyName: humidity
      bluetooth:
        characteristicUUID: fd02

status:
  twins:
    - propertyName: temperature
    - propertyName: humidity
