apiVersion: devices.kubeedge.io/v1alpha2
kind: DeviceModel
metadata:
  name: dth11-ble
  namespace: default
spec:
  properties:
    - name: temperature
      description: indicates the temperature value in degree Celsius
      type:
        float:
          defaultValue: 0
          unit: "Celsius"
          accessMode: ReadOnly
    - name: humidity
      description:
      type:
        float:
          defaultValue: 0
          accessMode: ReadOnly
