apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: led-ble-instance-01
  labels:
    description: led-light
    model: led-ble
spec:
  deviceModelRef:
    name: led-ble
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: "kubernetes.io/hostname"
            operator: In
            values:
              - jetson #pls give your edge node name
  protocol:
    bluetooth:
      macAddress: "8C:CE:4E:83:25:52"
  propertyVisitors:
    - propertyName: "power-status"
      bluetooth:
        characteristicUUID: ff01
        dataWrite:
          "ON": "0x01" #Here "ON" refers to the value of the property "temperature-enable" and [1] refers to the corresponding []byte value to be written into the device when the value of temperature-enable is "ON"
          "OFF": "0x00"
    - propertyName: gpio-pin-number
      bluetooth:
        characteristicUUID: ff02

status:
  twins:
    - propertyName: power-status
    - propertyName: gpio-pin-number
