apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: lock-wifi-instance-001
  labels:
    description: inteligence-lock
    model: lock-wifi
spec:
  deviceModelRef:
    name: lock-wifi
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: "kubernetes.io/hostname"
            operator: In
            values:
              - jetson #pls give your edge node name
  protocol:
    common:
      tcp: 
        ip: ${the ip of wifi device}
        port: ${the port of wifi device} 
      commonType: "tcp client"
  propertyVisitors:
    - propertyName: "power-status"
      bluetooth:
        characteristicUUID: ff01
        dataWrite:
          "ON": "0x01" #Here "ON" refers to the value of the property "temperature-enable" and [1] refers to the corresponding []byte value to be written into the device when the value of temperature-enable is "ON"
          "OFF": "0x00"
    - propertyName: gpio-pin-number
      bluetooth:
        characteristicUUID: ff02

status:
  twins:
    - propertyName: power-status
    - propertyName: gpio-pin-number