apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: smoke-ble-instances-001
  labels:
    description: mq2
    model: smoke-ble
spec:
  deviceModelRef:
    name: smoke-ble
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: "kubernetes.io/hostname"
            operator: In
            values:
              - jetsonnano.edge #pls give your edge node name
  protocol:
    bluetooth:
      macAddress: "8C:CE:4E:83:25:52"
  propertyVisitors:
    - propertyName: smoke
      bluetooth:
        characteristicUUID: fe01
    - propertyName: alarm
      bluetooth:
        characteristicUUID: fe02
        dataWrite:
          "ON": "0x01" #Here "ON" refers to the value of the property "temperature-enable" and [1] refers to the corresponding []byte value to be written into the device when the value of temperature-enable is "ON"
          "OFF": "0x00"

status:
  twins:
    - propertyName: smoke
    - propertyName: alarm
